"""Inspection lifecycle + vision endpoints (photo-first flow, ADR 0011).

Keeps the honesty contract at the API boundary: the overlay is only ever the
model's *predicted* mask, area is image-denominator, consent/training writes
flow exclusively through ``ConsentService``, and every analysis reply is
generated by the assistant service (LangChain when a key is set, an offline
stub otherwise). No cost or repair fields exist.
"""

from __future__ import annotations

import base64
import json
import logging
import uuid
from datetime import UTC, datetime
from typing import Annotated, Any, NoReturn, cast

from fastapi import APIRouter, File, HTTPException, Request, UploadFile

from apps.api.agent.assistant import (
    AssistantUnavailableError,
    StubAssistant,
)
from apps.api.agent.graph import (
    context_from_state,
    features_from_summary,
    persist_evidence,
)
from apps.api.container import Container
from apps.api.errors import (
    APIErrorCode,
    problem,
)
from apps.api.errors import (
    detail as problem_detail,
)
from apps.api.shared.schemas import (
    AnalyzeResponse,
    ConsentRequest,
    ConsentResponse,
    InspectionStateResponse,
    SessionCreated,
    UploadResponse,
)
from apps.api.storage.records import ConsentDecision, ImageKind, SessionStatus
from apps.api.vision.quality import ImageQualityValidator
from ml.inference.features import extract_features
from ml.inference.overlay import encode_png, render_overlay
from ml.inference.preprocess import load_image_rgb

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/inspection", tags=["inspection"])


def _container(request: Request) -> Container:
    return cast(Container, request.app.state.container)


def _raise(prob: Any) -> NoReturn:
    """Raise a typed HTTP problem (safe message, machine-readable code)."""
    raise HTTPException(status_code=prob.status_code, detail=problem_detail(prob))


def _valid_session(request: Request, session_id: str) -> Container:
    c = _container(request)
    record = c.sessions.get(session_id)
    if record is None:
        _raise(problem(404, APIErrorCode.SESSION_NOT_FOUND, "session not found"))
    if record.status is not SessionStatus.ACTIVE:
        _raise(problem(410, APIErrorCode.SESSION_CLOSED, "session closed"))
    if record.expires_at is not None and record.expires_at < datetime.now(UTC):
        _raise(problem(410, APIErrorCode.SESSION_EXPIRED, "session expired"))
    return c


def _load_state(c: Container, session_id: str) -> dict[str, Any]:
    raw = c.states.get(session_id)
    if raw:
        loaded = json.loads(raw)
        return {"session_id": session_id, **loaded}
    return {"session_id": session_id, "messages": []}


def _save_state(c: Container, session_id: str, state: dict[str, Any]) -> None:
    c.states.save(session_id, json.dumps(state, default=str))


@router.post("/session", response_model=SessionCreated)
def create_session(request: Request) -> SessionCreated:
    c = _container(request)
    session_id = uuid.uuid4().hex
    record = c.sessions.create(session_id)
    _save_state(c, session_id, {"session_id": session_id, "messages": []})
    return SessionCreated(
        session_id=record.session_id,
        status=record.status.value,
        created_at=record.created_at.isoformat(),
        expires_at=record.expires_at.isoformat() if record.expires_at else "",
    )


@router.post("/{session_id}/upload", response_model=UploadResponse)
def upload_photo(
    session_id: str, request: Request, file: Annotated[UploadFile, File()]
) -> UploadResponse:
    c = _valid_session(request, session_id)
    data = file.file.read()
    asset_id = uuid.uuid4().hex
    try:
        asset = c.images.write(session_id, asset_id, ImageKind.UPLOAD, data)
    except ValueError as exc:
        _raise(problem(400, APIErrorCode.BAD_UPLOAD, str(exc)))
    state = _load_state(c, session_id)
    state["image_asset_id"] = asset.asset_id  # a new photo supersedes the previous one
    _save_state(c, session_id, state)
    return UploadResponse(
        session_id=session_id,
        asset_id=asset.asset_id,
        kind=asset.kind.value,
        note="Photo stored for this session only; /analyze will inspect it.",
    )


def _llm_retake_guidance(c: Container, reasons: list[str]) -> tuple[str, bool]:
    """Live LLM guidance on the quality gate; offline fallback if Groq is down."""
    try:
        return c.assistant.retake_guidance(reasons=reasons), False
    except AssistantUnavailableError:
        logger.exception("LLM unavailable; using deterministic retake guidance")
        return StubAssistant().retake_guidance(reasons=reasons), True


def _llm_explanation(c: Container, evidence: dict[str, Any]) -> tuple[str, bool]:
    """Live LLM explanations of the evidence; offline summary if Groq is down."""
    try:
        return c.assistant.damages_explanation(evidence=evidence), False
    except AssistantUnavailableError:
        logger.exception("LLM unavailable; using deterministic evidence summary")
        return StubAssistant().damages_explanation(evidence=evidence), True


@router.post("/{session_id}/analyze", response_model=AnalyzeResponse)
def analyze_photo(session_id: str, request: Request) -> AnalyzeResponse:
    c = _valid_session(request, session_id)
    state = _load_state(c, session_id)
    asset_id = state.get("image_asset_id")
    asset = c.images.get(asset_id) if asset_id else None
    if asset is None:
        _raise(problem(404, APIErrorCode.NO_UPLOADED_PHOTO, "no uploaded photo for this session"))
    data = c.images.read(asset)

    rgb = load_image_rgb(data)
    quality = ImageQualityValidator().assess(rgb)
    quality_dict = quality.to_dict()

    user_photo_msg = {
        "role": "user",
        "content": "[Photo uploaded] — please analyse the damage.",
    }
    messages = [*state.get("messages", []), user_photo_msg]

    # Capture-quality gate (ADR 0007 contract): reject before any model inference
    # on dark/glare/blurry/low-contrast shots. These are user-fixable capture
    # problems, not model output. Guidance comes from the assistant; no mask is
    # ever produced for a rejected photo.
    if not quality.is_valid:
        guidance, fallback = _llm_retake_guidance(c, quality.reasons)
        state.update(
            {
                "messages": [*messages, {"role": "assistant", "content": guidance}],
                "quality": quality_dict,
                "inspection": None,
                "explanation": guidance,
            }
        )
        _save_state(c, session_id, state)
        return AnalyzeResponse(
            session_id=session_id,
            status="QUALITY_FAILED",
            assistant_message=guidance,
            assistant_fallback=fallback,
            asset_id=asset.asset_id,
            quality_status=quality.status.value,
            quality_reasons=quality.reasons,
        )

    try:
        engine = c.engine()
    except Exception:
        logger.exception("segmentation engine could not be built")
        _raise(problem(500, APIErrorCode.MODEL_UNAVAILABLE, "model unavailable"))

    try:
        result = engine.predict_bytes(data)
    except Exception:
        logger.exception("hybrid model forward pass failed")
        _raise(problem(500, APIErrorCode.INFERENCE_FAILED, "model inference failed"))

    features = extract_features(result)

    overlay_png = encode_png(render_overlay(rgb, result.mask))
    overlay_b64 = base64.b64encode(overlay_png).decode("ascii")
    c.images.write(session_id, uuid.uuid4().hex, ImageKind.OVERLAY, overlay_png)

    inspection = features.to_dict()
    inspection.update(
        {
            "mean_confidence": round(result.mean_confidence, 4),
            "damage_fraction": round(result.damage_fraction, 6),
            "low_confidence": result.quality.low_confidence,
            "model_notes": result.quality.notes,
            "quality": quality_dict,
            "model_metadata": result.metadata.to_dict(),
            "overlay_png_base64": overlay_b64,
        }
    )

    evidence = persist_evidence({"inspection": inspection})
    explanation, fallback = _llm_explanation(c, evidence or {})

    state.update(
        {
            "messages": [*messages, {"role": "assistant", "content": explanation}],
            "quality": quality_dict,
            "inspection": inspection,
            "explanation": explanation,
        }
    )
    _save_state(c, session_id, state)
    return AnalyzeResponse(
        session_id=session_id,
        status="OK",
        assistant_message=explanation,
        assistant_fallback=fallback,
        asset_id=asset.asset_id,
        quality_status=quality.status.value,
        quality_reasons=quality.reasons,
        inspection=inspection,
        classes_present={str(k): v for k, v in features.classes_present.items()},
        low_confidence=result.quality.low_confidence,
        damage_fraction=result.damage_fraction,
        mean_confidence=result.mean_confidence,
        overlay_png_base64=overlay_b64,
    )


@router.get("/{session_id}", response_model=InspectionStateResponse)
def get_inspection(session_id: str, request: Request) -> InspectionStateResponse:
    c = _valid_session(request, session_id)
    state = _load_state(c, session_id)
    return InspectionStateResponse(
        session_id=session_id,
        status="ACTIVE",
        state=state,
    )


@router.post("/{session_id}/consent", response_model=ConsentResponse)
def consent(session_id: str, request: Request, body: ConsentRequest) -> ConsentResponse:
    c = _valid_session(request, session_id)
    record = c.consent.record_decision(session_id, ConsentDecision(body.decision))
    sample_id: str | None = None
    saved = False
    note = "Decision recorded. The photos are not used for training."

    if record.decision is ConsentDecision.GRANTED:
        state = _load_state(c, session_id)
        inspection = state.get("inspection") or {}
        try:
            stored = c.consent.store_training_sample(
                context_from_state(state),
                features_from_summary(inspection),
                consent=record,
                image_asset_id=state.get("image_asset_id") or "",
            )
            if stored.get("saved"):
                saved = True
                sample_id = str(stored.get("sample_id"))
                note = (
                    "Anonymised sample stored for the consent dataset (MODEL_SUGGESTED provenance)."
                )
            else:
                note = "Consent granted, but no training sample could be stored."
        except Exception as exc:  # never leak internals to the client
            note = f"Consent granted, but sample storage failed: {exc}"

    return ConsentResponse(
        session_id=session_id,
        decision=record.decision.value,
        dataset_version=record.dataset_version or "",
        sample_id=sample_id,
        saved=saved,
        note=note,
    )


@router.delete("/{session_id}")
def delete_inspection(session_id: str, request: Request) -> dict[str, str]:
    c = _container(request)
    if not c.cleanup.cleanup(session_id):
        _raise(problem(404, APIErrorCode.SESSION_NOT_FOUND, "session not found"))
    return {"session_id": session_id, "status": "deleted"}
